// frontend/src/components/Summarizer.jsx
import React, { useState } from 'react';
import { authenticatedFetch } from '../api';
import { useLocalStorage } from '../hooks/useLocalStorage'; // Import the new hook

const Summarizer = () => {
  const [text, setText] = useState('');
  const [summary, setSummary] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  // Use the custom hook for history, giving it a unique key
  const [history, setHistory] = useLocalStorage('summarizer-history', []);

  const handleSummarize = async () => {
    if (!text) {
      setError('Please enter some text to summarize.');
      return;
    }
    setIsLoading(true);
    setError('');
    setSummary('');

    try {
      const data = await authenticatedFetch('/summarize', {
        method: 'POST',
        body: JSON.stringify({ text }),
      });
      setSummary(data.summary);
      // Add to history, keeping the most recent 5 items
      setHistory(prevHistory => [{ request: text, response: data.summary }, ...prevHistory].slice(0, 5));
    } catch (err) {
      setError(err.message || 'An unexpected error occurred.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="rounded-lg bg-white p-6 shadow-md">
        <h3 className="mb-2 text-lg font-semibold">Summarize Your Text</h3>
        <p className="mb-4 text-gray-600">
          Paste your long-form content below and get a concise summary generated by AI.
        </p>
        
        <textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          className="w-full rounded-md border border-gray-300 p-3 focus:border-blue-500 focus:ring-blue-500"
          rows="10"
          placeholder="Paste your text here..."
          disabled={isLoading}
        ></textarea>
        
        <button
          onClick={handleSummarize}
          disabled={isLoading}
          className="mt-4 w-full rounded-md bg-blue-600 px-6 py-3 font-semibold text-white transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:bg-blue-400 sm:w-auto"
        >
          {isLoading ? 'Generating...' : 'Generate Summary'}
        </button>

        {error && <p className="mt-4 rounded-md bg-red-100 p-3 text-red-600">{error}</p>}
        
        {summary && (
          <div className="mt-6 rounded-md bg-gray-50 p-4">
            <h4 className="font-semibold text-gray-800">Generated Summary:</h4>
            <p className="mt-2 whitespace-pre-wrap text-gray-700">{summary}</p>
          </div>
        )}
      </div>

      {history.length > 0 && (
        <div className="rounded-lg bg-white p-6 shadow-md">
          <h3 className="mb-4 text-lg font-semibold">History</h3>
          <ul className="space-y-4">
            {history.map((item, index) => (
              <li key={index} className="rounded-md border p-4">
                <p className="mb-2 text-sm font-semibold text-gray-500">Request:</p>
                <p className="mb-3 line-clamp-3 text-gray-700">{item.request}</p>
                <p className="mb-2 text-sm font-semibold text-gray-500">Response:</p>
                <p className="whitespace-pre-wrap text-gray-700">{item.response}</p>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
};

export default Summarizer;
